# Generated by Django 2.1.1 on 2019-03-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190317_1245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
